apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demoapp

resources:
  - namespace.yaml
  - ../../base

images:
  - name: ghcr.io/ops-nc/demoapp
    newTag: main

replicas:
  - name: demoapp
    count: 2

# httproute-patch : hostname demoapp.k8s.lab.ops.nc
# commit-patch    : ENV COMMIT, réécrit par la CI pour forcer le redéploiement ArgoCD
patches:
  - path: httproute-patch.yaml
  - path: commit-patch.yaml
