apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demoapp

resources:
  - namespace.yaml
  - ../../base

images:
  - name: ghcr.io/ops-nc/demoapp
    newTag: main

replicas:
  - name: demoapp
    count: 2

# hostname de l'HTTPRoute : demoapp.k8s.lab.ops.nc
patches:
  - path: httproute-patch.yaml
