apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demoapp-dev

resources:
  - namespace.yaml
  - ../../base

images:
  - name: ghcr.io/ops-nc/demoapp
    newTag: dev

replicas:
  - name: demoapp
    count: 1

# hostname de l'HTTPRoute : dev.demoapp.k8s.lab.ops.nc
patches:
  - path: httproute-patch.yaml
